version: "3"
services:
    redis:
        image: redis:4.0-alpine
        container_name: fairs-redis
        restart: always
        ports:
            - "6379:6379"
        # volumes:
        #     - ./data/redis:/data
    postgres:
        image: postgres:10-alpine
        container_name: fairs-postgres
        restart: always
        ports:
            - "6543:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=fairs-test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        